---
- hosts: all
  vars:
    project_name: textFilesStorage
    repo_name: fly1ngDream/text-files-storage
  tasks:
  - name: Dependencies
    tags: apt
    apt: cache_valid_time=3600 name={{ packages }}
    become: yes
    vars:
      packages:
        - antiword
        - python3
        - python-pip
        - python3-pip
        - python3-setuptools
  - name: Install pipenv
    tags: python
    become: yes
    shell: pip3 install pipenv
    register: pipenv
    changed_when: "'installed pipenv' in pipenv.stdout"
  - include_tasks: pyenv.yml
  - name: Clone repo
    tags: deploy
    git:
      repo: https://github.com/{{ repo_name }}
      update: yes
      force: yes
      dest: ~/{{ project_name }}
  - name: Install pipenv deps
    shell: pipenv install
    tags: pipenvdeps
    args:
      chdir: ~/{{ project_name }}
  - name: Set environment to production
    tags: deploy
    lineinfile:
      path: "{{ project_name }}/{{ project_name }}/settings/__init__.py"
      regexp: 'from \.\w+ import \*'
      line: 'from .prod import *'
  - name: Migrate db
    tags: deploy
    shell: pipenv run python manage.py migrate
    args:
      chdir: ~/{{ project_name }}
  - name: Collect static files
    tags: deploy
    shell: pipenv run python manage.py collectstatic --noinput
    args:
      chdir: ~/{{ project_name }}
  - name: Kill gunicorn
    shell: pkill gunicorn
    register: kill_gunicorn
    changed_when: kill_gunicorn.rc == 0
    failed_when: kill_gunicorn.rc not in [0, 1]
  - name: Run app
    tags: deploy
    shell: pipenv run gunicorn -D -b 0.0.0.0 {{ project_name }}.wsgi
    args:
      chdir: ~/{{ project_name }}
