---
- name: Dependencies
  apt: cache_valid_time=3600 name={{ item }}
  become: yes
  loop:
    - mosh
    - python3
    - python3-pip
    - python3-setuptools
- name: Install pipenv
  tags:
    - pip
  become: no
  pip: name=pipenv
